title: Joel Holder's - Loose Leaf Experiments
description: Notes, builds, and experiments.
url: "https://jclosure.github.io"
baseurl: "/blog"
theme: jekyll-theme-hacker
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
