title: Joel Holder's - Loose Leaf Experiments
description: Notes, builds, and experiments.
url: "http://joelholder.com"
baseurl: ""
theme: jekyll-theme-hacker
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
